def pbCrafting(type,event)
if type==:CRAFTINGBENCH
 cmd = pbMessage(_INTL("What are you going to do?"),[
                            _INTL("Craft"),
                            _INTL("Pick Up"),
                            _INTL("Cancel")])
		  if cmd==0
		  pbItemCrafter([
		  [:BEDROLL,[:WOODENPLANKS,3,:WOOL,3]],
		  [:CRAFTINGBENCH,[:WOODENPLANKS,5]],
		  [:APRICORNCRAFTING,[:WOODENPLANKS,6,:STONE,2]],
		  [:FURNACE,[:STONE,6]],
		  [:PORTABLEPC,[:WOODENPLANKS,5,:IRON2,3,:POKEBALL,5]],
		  [:ITEMCRATE,[:WOODENPLANKS,5,:IRON2,3,:LIGHTCLAY,7]],
		  [:CAULDRON,[:IRON2,6]],
		  [:UPGRADEDCRAFTINGBENCH,[:CRAFTINGBENCH,1,:SILVER2,4]],
		  [:HEALPOWDER,[:CHERIBERRY,0.50]],
		  [:ENERGYPOWDER,[:SITRUSBERRY,0.50]],
		  [:BERRYJUICE,[:ORANBERRY,1]],
		  [:WOODENPLANKS,[:ACORN,1]],
		  [:OLDROD,[:WOODENPLANKS,2]],
		  [:BOWL,[:WOODENPLANKS,3]],
		  [:FOODBAG,[:WOODENPLANKS,1]],
		  [:MACHETE,[:IRON2,2,:WOODENPLANKS,1]],
		  [:GOODROD,[:OLDROD,1,:IRON2,2]],
		  [:PICKAXE,[:WOODENPLANKS,2,:IRON2,3]],
		  [:WATERBOTTLE,[:IRON2,1]],
		  [:EXPALL,[:EXPSHARE,5,:IRON2,10]],
		  [:GROWTHMULCH,[:BALMMUSHROOM,3,:MOOMOOMILK,1]],
		  [:DAMPMULCH,[:REDAPRICORN,2,:FRESHWATER,3]],
		  [:STABLEMULCH,[:MIRACLESEED,2,:FRESHWATER,1]],
		  [:GOOEYMULCH,[:MOOMOOMILK,1,:BLUEAPRICORN,1]],
		  [:PRODUCEMULCH,[:LEFTOVERS,0.5,:MOOMOOMILK,1]],
		  [:POTENTIALMULCH,[:BALMMUSHROOM,1,:FRESHWATER,2]],
		  [:RARECANDY,[:CORNNBERRY,30,:MAGOSTBERRY,30]],
		  [:HPUP,[:CORNNBERRY,10]],
		  [:PPUP,[:MAGOSTBERRY,10]],
		  [:IRON,[:GANLONBERRY,10]],
		  [:CALCIUM,[:PETAYABERRY,10]],
		  [:ZINC,[:APICOTBERRY,10]],
		  [:CARBOS,[:SALACBERRY,1]],
		  [:BLACKFLUTE,[:SOFTSAND,4,:CHARCOAL,4]],
		  [:STONE,[:HARDSTONE,1]]
		  ])
		  else cmd==1
		    message=_INTL("Do you want to pick up your {1}",type)
			if pbConfirmMessage(message)
			  Kernel.pbReceiveItem((type))
			  pbSetSelfSwitch(event, "A", false)
		    end
          end

elsif type==:APRICORNCRAFTING
 cmd = pbMessage(_INTL("What are you going to do?"),[
                            _INTL("Craft"),
                            _INTL("Pick Up"),
                            _INTL("Cancel")])
		  if cmd==0
		  pbItemCrafter([
[:POKEBALL,[:REDAPRICORN,1]],
[:GREATBALL,[:REDAPRICORN,2,:BLUEAPRICORN,1]],
[:ULTRABALL,[:BLACKAPRICORN,2,:YELLOWAPRICORN,1,:REDAPRICORN,1]],
[:SUPERBALL,[:REDAPRICORN,4,:PINKAPRICORN,1,:BLACKAPRICORN,2]],
[:PREMIERBALL,[:WHITEAPRICORN,1,:POKEBALL,1]],
[:MASTERBALL,[:PURPLEAPRICORN,2,:ENIGMABERRY,2,:COMETSHARD,1]],
[:NETBALL,[:BLACKAPRICORN,1,:WHITEAPRICORN,2]],
[:SHOCKBALL,[:YELLOWAPRICORN,3,:WHITEAPRICORN,2]],
[:MOONBALL,[:YELLOWAPRICORN,2,:BLACKAPRICORN,1]],
[:LUREBALL,[:REDAPRICORN,1,:BLUEAPRICORN,2]],
[:LEVELBALL,[:BLACKAPRICORN,2,:REDAPRICORN,1]],
[:HEAVYBALL,[:BLUEAPRICORN,2]],
[:LOVEBALL,[:WHITEAPRICORN,2]],
[:SPORTBALL,[:REDAPRICORN,2,:WHITEAPRICORN,1]],
[:SAFARIBALL,[:GREENAPRICORN,2,:YELLOWAPRICORN,1]],
[:FRIENDBALL,[:GREENAPRICORN,2,:WHITEAPRICORN,1]],
[:NESTBALL,[:GREENAPRICORN,2,:YELLOWAPRICORN,1,:TANGABERRY,1]],
[:REPEATBALL,[:REDAPRICORN,1,:BLACKAPRICORN,2,:JABOCABERRY,3]],
[:LUXURYBALL,[:REDAPRICORN,1,:WHITEAPRICORN,2]],
[:DIVEBALL,[:PINKAPRICORN,1,:BLUEAPRICORN,2,:PASSHOBERRY,2]],
[:TIMERBALL,[:WHITEAPRICORN,2,:BLACKAPRICORN,1,:DURINBERRY,2]],
[:DUSKBALL,[:BLACKAPRICORN,2,:BLUEAPRICORN,1,:BLUKBERRY,2]],
[:HEALBALL,[:PINKAPRICORN,1,:WHITEAPRICORN,2,:ORANBERRY,5]],
[:QUICKBALL,[:YELLOWAPRICORN,1,:BLUEAPRICORN,2,:CUSTAPBERRY,2]],
[:CHERISHBALL,[:REDAPRICORN,1,:POKEBALL,2]],
[:STATUSBALL,[:WHITEAPRICORN,2,:REDAPRICORN,5,:PECHABERRY,4]],
[:BURNBALL,[:REDAPRICORN,3,:GREENAPRICORN,1,:RAWSTBERRY,4]],
[:DREAMBALL,[:BLACKAPRICORN,1,:PINKAPRICORN,3,:CHESTOBERRY,4]],
[:FREEZEBALL,[:BLUEAPRICORN,3,:WHITEAPRICORN,3,:ASPEARBERRY,4]],
[:STUNBALL,[:YELLOWAPRICORN,2,:PINKAPRICORN,3,:CHERIBERRY,4]],
[:TOXICBALL,[:BLACKAPRICORN,3,:GREENAPRICORN,2,:PECHABERRY,4]],
[:BARBEDBALL,[:GREENAPRICORN,2,:BLACKAPRICORN,2,:IRON2,1]],
[:YOLOBALL,[:REDAPRICORN,4,:PINKAPRICORN,1,:SHUCABERRY,1]],
[:STATUSBALL,[:BLACKAPRICORN,2,:PINKAPRICORN,3,:STARFBERRY,1]],
[:HIDDENBALL,[:PINKAPRICORN,8,:GREENAPRICORN,8,:CUSTAPBERRY,5]],
[:IMMUNEBALL,[:BLACKAPRICORN,1,:WHITEAPRICORN,3,:CHILANBERRY,2]],
[:DEBUFFBALL,[:REDAPRICORN,1,:BLACKAPRICORN,3,:YELLOWAPRICORN,3]],
[:DAWNBALL,[:WHITEAPRICORN,1,:YELLOWAPRICORN,1]]
		  ])
		  else cmd==1
		    message=_INTL("Do you want to pick up your {1}",type)
			if pbConfirmMessage(message)
			  Kernel.pbReceiveItem((type))
			  pbSetSelfSwitch(event, "A", false)
		    end
          end

elsif type==:MEDICINEPOT
 cmd = pbMessage(_INTL("What are you going to do?"),[
                            _INTL("Craft"),
                            _INTL("Pick Up"),
                            _INTL("Cancel")])
		  if cmd==0
          pbItemCrafter([
[:REVIVE,[:ARGOSTBERRY,5,:QUALOTBERRY,3,:IRON2,2]],
[:MAXREVIVE,[:REVIVE,1,:ARGOSTBERRY,3,:REVIVALHERB,2,:IRON2,2]],
[:POTION,[:ORANBERRY,1,:IRON2,1]],
[:SUPERPOTION,[:POTION,1,:SITRUSBERRY,2,:QUALOTBERRY,1]],
[:HYPERPOTION,[:SUPERPOTION,1,:SITRUSBERRY,3,:QUALOTBERRY,3]],
[:FULLRESTORE,[:HYPERPOTION,1,:SITRUSBERRY,3,:QUALOTBERRY,5,:HONDEWBERRY,3]]
])
		  else cmd==1
		    message=_INTL("Do you want to pick up your {1}",type)
			if pbConfirmMessage(message)
			  Kernel.pbReceiveItem((type))
			  pbSetSelfSwitch(event, "A", false)
		    end
          end
elsif type==:UPGRADEDCRAFTINGBENCH
 cmd = pbMessage(_INTL("What are you going to do?"),[
                            _INTL("Craft"),
                            _INTL("Pick Up"),
                            _INTL("Cancel")])
		  if cmd==0
  if $game_switches[169] == true 
    pbItemCrafter([
[:BEDROLL,[:WOODENPLANKS,3,:WOOL,3]],
[:CRAFTINGBENCH,[:WOODENPLANKS,5]],
[:APRICORNCRAFTING,[:WOODENPLANKS,6,:STONE,2]],
[:FURNACE,[:STONE,6]],
[:PORTABLEPC,[:WOODENPLANKS,5,:IRON2,3,:POKEBALL,5]],
[:ITEMCRATE,[:WOODENPLANKS,5,:IRON2,3,:LIGHTCLAY,7]],
[:CAULDRON,[:IRON2,6]],
[:UPGRADEDCRAFTINGBENCH,[:CRAFTINGBENCH,1,:SILVER2,4]],
[:GRINDER,[:STONE,5,:IRON2,3]],
[:MEDICINEPOT,[:CLAY2,6,:CHARCOAL,3]],
[:PORTABLECAMP,[:WOOL,5,:WOODENPLANKS,5,:COPPER2,2]],
[:SPRINKLER,[:STONE,5,:IRON2,3]],
[:ELECTRICGRINDER,[:CLAY2,6,:CHARCOAL,3,:GRINDER,1]],
[:ELECTRICFURNACE,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:ELECTRICPRESS,[:COPPER2,2,:IRON2,40,:STONE,5]],
[:APRICORNMACHINE,[:COPPER2,8,:SILVER2,2,:APRICORNCRAFTING,2,:STONE,20]],
[:SEWINGMACHINE,[:COPPER2,4,:IRON2,5,:CRAFTINGBENCH,2,:STONE,5]],
[:CUTTER,[:COPPER2,4,:IRON2,7,:WOODENPLANKS,50,:STONE,5]],
[:COALGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:SOLARGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:WINDGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:HYDROGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:POKEGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]]
])
elsif $game_switches[409] == true 
    pbItemCrafter([
[:BEDROLL,[:WOODENPLANKS,3,:WOOL,3]],
[:CRAFTINGBENCH,[:WOODENPLANKS,5]],
[:APRICORNCRAFTING,[:WOODENPLANKS,6,:STONE,2]],
[:FURNACE,[:STONE,6]],
[:PORTABLEPC,[:WOODENPLANKS,5,:IRON2,3,:POKEBALL,5]],
[:ITEMCRATE,[:WOODENPLANKS,5,:IRON2,3,:LIGHTCLAY,7]],
[:CAULDRON,[:IRON2,6]],
[:UPGRADEDCRAFTINGBENCH,[:CRAFTINGBENCH,1,:SILVER2,4]],
[:GRINDER,[:STONE,5,:IRON2,3]],
[:MEDICINEPOT,[:CLAY2,6,:CHARCOAL,3]],
[:PORTABLECAMP,[:WOOL,5,:WOODENPLANKS,5,:COPPER2,2]],
[:SPRINKLER,[:STONE,5,:IRON2,3]],
[:ELECTRICGRINDER,[:CLAY2,6,:CHARCOAL,3,:GRINDER,1]],
[:ELECTRICFURNACE,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]],
[:ELECTRICPRESS,[:COPPER2,2,:IRON2,40,:STONE,5]],
[:APRICORNMACHINE,[:COPPER2,8,:SILVER2,2,:APRICORNCRAFTING,2,:STONE,20]],
[:SEWINGMACHINE,[:COPPER2,4,:IRON2,5,:CRAFTINGBENCH,2,:STONE,5]],
[:CUTTER,[:COPPER2,4,:IRON2,7,:WOODENPLANKS,50,:STONE,5]]
])
elsif $game_switches[498] == true 
pbItemCrafter([
[:BEDROLL,[:WOODENPLANKS,3,:WOOL,3]],
[:CRAFTINGBENCH,[:WOODENPLANKS,5]],
[:APRICORNCRAFTING,[:WOODENPLANKS,6,:STONE,2]],
[:FURNACE,[:STONE,6]],
[:PORTABLEPC,[:WOODENPLANKS,5,:IRON2,3,:POKEBALL,5]],
[:ITEMCRATE,[:WOODENPLANKS,5,:IRON2,3,:LIGHTCLAY,7]],
[:CAULDRON,[:IRON2,6]],
[:UPGRADEDCRAFTINGBENCH,[:CRAFTINGBENCH,1,:SILVER2,4]],
[:GRINDER,[:STONE,5,:IRON2,3]],
[:MEDICINEPOT,[:CLAY2,6,:CHARCOAL,3]],
[:PORTABLECAMP,[:WOOL,5,:WOODENPLANKS,5,:COPPER2,2]],
[:COALGENERATOR,[:COPPER2,8,:IRON2,30,:FURNACE,4,:STONE,10]]
])
else
pbItemCrafter([
[:BEDROLL,[:WOODENPLANKS,3,:WOOL,3]],
[:CRAFTINGBENCH,[:WOODENPLANKS,5]],
[:APRICORNCRAFTING,[:WOODENPLANKS,6,:STONE,2]],
[:FURNACE,[:STONE,6]],
[:PORTABLEPC,[:WOODENPLANKS,5,:IRON2,3,:POKEBALL,5]],
[:ITEMCRATE,[:WOODENPLANKS,5,:IRON2,3,:LIGHTCLAY,7]],
[:CAULDRON,[:IRON2,6]],
[:UPGRADEDCRAFTINGBENCH,[:CRAFTINGBENCH,1,:SILVER2,4]],
])
end
		  else cmd==1
		    message=_INTL("Do you want to pick up your {1}",type)
			if pbConfirmMessage(message)
			  Kernel.pbReceiveItem((type))
			  pbSetSelfSwitch(event, "A", false)
		    end
          end
#elsif type==:GRINDER
#elsif type==:FURNACE
#elsif type==:PORTABLEPC
#elsif type==:BEDROLL
#elsif type==:ITEMCRATE
end